### ISSUE TITLE
cbow modelling

### ISSUE THREAD

**Issue by inancarin** [wangz10/tensorflow-playground#1]
Hi wangz10,

I am trying to implement your cbow model. I updated google's tensorflow generate_batch function accordingly. However, when user enters n words (let's say "He was born in England, he speaks"), the cbow should predict "English" as result (or some language at least). In that case, should my num_skips be 7? How to modify your fit function (in word2vec.py) in order to predict above validation sample?

Or is my use case defined above more about RNN and is cbow model only capable of predicting "was" when I input ["he", "born"]?  

Thanks

**Comment by wangz10** [comment]
Hi @inancarin ,

Based on my understanding of word2vec, your example "He was born in England, he speaks" -> "English" can only be predicted by Skip-gram rather than CBOW. Because CBOW use the surrounding words to predict the middle word. 

Take a look at [this question](http://stackoverflow.com/questions/37394970/tensorflow-word2vec-cbow-model) or the [original paper](https://arxiv.org/pdf/1301.3781v3.pdf).

Z

**Comment by inancarin** [comment]
Thanks @wangz10
